# mssql-server-agent-fts-ha-tools

# Base OS layer: Red Hat 8 ubi

FROM registry.access.redhat.com/ubi8

USER root

# Install prerequistes since it is needed to get repo config for SQL server

RUN yum -y update
